SET DEFINE OFF;
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Nb', 0.02, 0.01, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'V', 0.004, 0.001, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'C', 0.18, 0.16, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'Mn', 0.8, 0.75, 0.85);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-1', 'Nb', 0.013, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'C', 0.18, 0.16, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'Mn', 0.85, 0.8, 0.95);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'Al', 0.006, 0.005, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-2', 'Nb', 0.013, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'C', 0.18, 0.16, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'Mn', 1, 0.95, 1.05);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'Al', 0.01, 0.005, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-3', 'Nb', 0.013, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'C', 0.08, 0.06, 0.1);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'Si', 0.2, 0.15, 0.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'Mn', 1.5, 1.45, 1.55);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'P', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'S', 0.005, 0, 0.007);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'Al', 0.025, 0.015, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'Ti', 0.02, 0, 0.04);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'V', 0.05, 0.04, 0.06);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X60', 'Nb', 0.04, 0.035, 0.045);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Al', 0.05, 0.04, 0.06);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Mo', 0.01, 0.01, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Ti', 0.02, 0.01, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'C', 0.05, 0, 0.07);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'Si', 0.2, 0.15, 0.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'Mn', 1.5, 1.4, 1.6);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'P', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'S', 0.002, 0, 0.005);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'Al', 0.03, 0.02, 0.045);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'Mo', 0.12, 0.1, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'Ti', 0.018, 0.015, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'V', 0.045, 0.03, 0.06);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X70', 'Nb', 0.065, 0.055, 0.075);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'C', 0.06, 0.04, 0.08);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'Si', 0.08, 0.05, 0.12);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'Mn', 0.65, 0.55, 0.75);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'P', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'S', 0.005, 0, 0.007);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'Al', 0.02, 0.02, 0.04);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R(TC)', 'Ti', 0.14, 0.13, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'C', 0.13, 0.11, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'Si', 0.28, 0.2, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'Mn', 1.35, 1.3, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'P', 0.015, 0, 0.018);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'S', 0.005, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'Al', 0.03, 0.025, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qE', 'Nb', 0.015, 0.013, 0.017);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'C', 0.13, 0.11, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'Si', 0.28, 0.25, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'Mn', 1.35, 1.3, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'P', 0.015, 0, 0.022);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'S', 0.005, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'Al', 0.03, 0.025, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345GJC', 'Nb', 0.015, 0.013, 0.017);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'C', 0.12, 0.11, 0.14);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'Si', 0.25, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'Mn', 1.1, 1.05, 1.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'P', 0.015, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'Al', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X42', 'Nb', 0.012, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'C', 0.08, 0.07, 0.09);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'Si', 0.25, 0.2, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'Mn', 0.98, 0.93, 1.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'P', 0.015, 0, 0.019);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'S', 0.003, 0, 0.005);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'Al', 0.03, 0.025, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'Ti', 0.035, 0.03, 0.038);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('X52', 'Nb', 0.032, 0.028, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'C', 0.16, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'Si', 0.2, 0.15, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'Mn', 0.8, 0.75, 0.85);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'P', 0.025, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'Al', 0.01, 0.005, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-1', 'B', 0.0012, 0.001, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'C', 0.16, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'Si', 0.2, 0.15, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'Mn', 0.9, 0.85, 0.95);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'P', 0.025, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'Al', 0.01, 0.005, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'Ti', 0.02, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-2', 'B', 0.0012, 0.001, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'C', 0.16, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'Si', 0.2, 0.15, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'Mn', 1, 0.95, 1.05);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'P', 0.025, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'Al', 0.01, 0.005, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S275JR-B-3', 'B', 0.0012, 0.001, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-1', 'C', 0.16, 0.15, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-1', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-1', 'Mn', 0.45, 0.35, 0.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-1', 'P', 0.035, 0, 0.04);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-1', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-1', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-2', 'C', 0.17, 0.15, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-2', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-2', 'Mn', 0.45, 0.35, 0.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-2', 'P', 0.035, 0, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-2', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-2', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-3', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-3', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-3', 'Mn', 0.4, 0.35, 0.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-3', 'P', 0.035, 0, 0.04);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-3', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-3', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235C', 'C', 0.16, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235C', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235C', 'Mn', 0.65, 0.6, 0.75);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235C', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235C', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235C', 'Al', 0.01, 0.005, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235D', 'C', 0.15, 0.13, 0.16);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235D', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235D', 'Mn', 0.8, 0.75, 0.85);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235D', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235D', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235D', 'Al', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-4', 'C', 0.16, 0.15, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-4', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-4', 'Mn', 1.3, 1.2, 1.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-4', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-4', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-4', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-5', 'C', 0.17, 0.15, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-5', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-5', 'Mn', 1.35, 1.3, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-5', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-5', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-5', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-6', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-6', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-6', 'Mn', 1.25, 1.2, 1.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-6', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-6', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-6', 'Al', 0.006, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'C', 0.15, 0.14, 0.16);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'Mn', 1.2, 1.15, 1.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'P', 0.018, 0, 0.23);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345E', 'Nb', 0.015, 0.01, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'C', 0.16, 0.15, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'Mn', 1.4, 1.34, 1.45);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'P', 0.025, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'Al', 0.012, 0.008, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-B', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'C', 0.17, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'Mn', 0.45, 0.4, 0.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'P', 0.03, 0, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SS400-B', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'C', 0.17, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'Mn', 0.45, 0.4, 0.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'P', 0.03, 0, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-B', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'C', 0.16, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'Mn', 1.2, 1.15, 1.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-1', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'C', 0.16, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'Mn', 1.3, 1.25, 1.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('SM490A-B-2', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'C', 0.17, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'Mn', 0.9, 0.85, 0.95);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'P', 0.03, 0, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-1', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'C', 0.17, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'Mn', 0.65, 0.6, 0.7);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'P', 0.03, 0, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA36-B-2', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'C', 0.16, 0.15, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'Mn', 1.3, 1.25, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('350', 'B', 0.001, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'C', 0.16, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'Si', 0.025, 0.2, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'Mn', 1.2, 1.15, 1.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'Al', 0.015, 0.01, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S355', 'Nb', 0.013, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'Mn', 1.35, 1.3, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'Al', 0.01, 0.005, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\D-1', 'Ti', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'Mn', 1.45, 1.4, 1.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'Al', 0.01, 0.005, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345C\ D-2', 'Ti', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'Mn', 1.35, 1.3, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q390C\ D-3', 'Ti', 0.013, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-A', 'C', 0.16, 0.15, 0.19);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-A', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-A', 'Mn', 0.55, 0.5, 0.6);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-A', 'P', 0.025, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-A', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-A', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-B', 'C', 0.16, 0.14, 0.18);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-B', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-B', 'Mn', 0.65, 0.62, 0.7);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-B', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-B', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-B', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-D', 'C', 0.12, 0.11, 0.14);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-D', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-D', 'Mn', 1.05, 1, 1.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-D', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-D', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Grade-D', 'Al', 0.03, 0.02, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'Mn', 1, 0.95, 1.05);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH32', 'Nb', 0.012, 0.01, 0.018);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'Mn', 1, 0.95, 1.05);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH32', 'Nb', 0.012, 0.01, 0.018);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'Mn', 1.2, 1.15, 1.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('AH36', 'Nb', 0.013, 0.01, 0.018);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'Mn', 1.2, 1.15, 1.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('DH36', 'Nb', 0.013, 0.01, 0.018);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'Mn', 1.4, 1.35, 1.45);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'Al', 0.015, 0.01, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-1', 'V', 0.035, 0.03, 0.04);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'Mn', 1.45, 1.35, 1.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'Al', 0.015, 0.01, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q460D-2', 'V', 0.07, 0.06, 0.08);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'Mn', 1.4, 1.35, 1.45);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420B/C/D', 'Nb', 0.02, 0.018, 0.023);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('45', 'C', 0.47, 0.42, 0.48);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('45', 'Si', 0.25, 0.2, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('45', 'Mn', 0.6, 0.55, 0.65);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('45', 'P', 0.015, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('45', 'S', 0.02, 0, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('45', 'Al', 0.01, 0.008, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'C', 0.45, 0.44, 0.47);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'Si', 0.25, 0.2, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'Mn', 0.65, 0.6, 0.7);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'P', 0.015, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'S', 0.015, 0.005, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'Al', 0.01, 0.008, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'Ti', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('S45C-B', 'B', 0.00125, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'C', 0.12, 0.11, 0.13);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'Mn', 1.2, 1.15, 1.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'P', 0.025, 0.02, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'S', 0.01, 0.005, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'Ti', 0.025, 0.2, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345B-Z15', 'Nb', 0.018, 0.015, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'C', 0.16, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'Mn', 1.35, 1.3, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'P', 0.015, 0, 0.023);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'Al', 0.01, 0.005, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345R', 'Ti', 0.025, 0.2, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-1', 'C', 0.16, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-1', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-1', 'Mn', 0.4, 0.3, 0.5);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-1', 'P', 0.02, 0, 0.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-1', 'S', 0.005, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-1', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-2', 'C', 0.16, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-2', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-2', 'Mn', 0.45, 0.35, 0.55);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-2', 'P', 0.015, 0, 0.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-2', 'S', 0.005, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-Z15-2', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'Mn', 1.15, 1.1, 1.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'S', 0.012, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'Nb', 0.012, 0.01, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('ASTMA572', 'B', 0.0012, 0.001, 0.0015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qC/D', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qC/D', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qC/D', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qC/D', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qC/D', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345qC/D', 'Ti', 0.018, 0.012, 0.022);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'Mn', 1.3, 1.25, 1.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q370qC/D', 'Nb', 0.015, 0.013, 0.017);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('PSL1-B', 'C', 0.15, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('PSL1-B', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('PSL1-B', 'Mn', 0.65, 0.6, 0.7);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('PSL1-B', 'P', 0.02, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('PSL1-B', 'S', 0.01, 0, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('PSL1-B', 'Al', 0.01, 0.005, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'C', 0.16, 0.15, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'Si', 0.2, 0.15, 0.35);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'Mn', 1.35, 1.35, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'P', 0.015, 0.015, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q420QD', 'Nb', 0.015, 0.013, 0.017);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245PSL2B ', 'C', 0.09, 0, 0.1);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245PSL2B ', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245PSL2B ', 'Mn', 0.75, 0.7, 1.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245PSL2B ', 'P', 0.02, 0, 0.025);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245PSL2B ', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245PSL2B ', 'Al', 0.01, 0.005, 0.015);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R', 'C', 0.15, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R', 'Mn', 0.75, 0.7, 0.8);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R', 'P', 0.02, 0, 0.023);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q245R', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-1', 'C', 0.15, 0.14, 0.17);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-1', 'Si', 0.15, 0.1, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-1', 'Mn', 0.75, 0.7, 0.8);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-1', 'P', 0.02, 0, 0.023);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-1', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-1', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-2', 'C', 0.12, 0.1, 0.14);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-2', 'Si', 0.15, 0.1, 0.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-2', 'Mn', 1, 0.9, 1.05);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-2', 'P', 0.02, 0, 0.023);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-2', 'S', 0.008, 0, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('L245\PSL1/2B-2', 'Al', 0.025, 0.02, 0.3);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-4', 'C', 0.08, 0.07, 0.1);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-4', 'Si', 0.15, 0.15, 0.25);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-4', 'Mn', 0.55, 0.5, 0.6);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-4', 'P', 0.025, 0, 0.03);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-4', 'S', 0.015, 0, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235B-4', 'Al', 0.015, 0.01, 0.2);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'C', 0.5, 0.03, 1);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'Cr', 0.01, 0.005, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'Cu', 0.3, 0, 0.4);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'Mn', 0.01, 0.005, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'N', 0.14, 0.13, 0.15);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'Ni', 3.55, 3.53, 3.6);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'P', 0.05, 0, 0.06);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'S', 0.007, 0, 0.008);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q345', 'Si', 0.03, 0.02, 0.035);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'C', 0.05, 0.04, 0.06);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Cr', 0.1, 0.12, 0.14);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Cu', 0.1, 0.08, 0.12);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Mn', 0.5, 0.4, 0.6);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'N', 0.005, 0.004, 0.006);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Ni', 0.1, 0.08, 0.12);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'P', 0.015, 0.01, 0.02);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'S', 0.008, 0.008, 0.01);
Insert into L2CCS.GCC_SPEC_ANALYSIS
   (GRADE_CODE, ELEMENT_NAME, AIM_CONC, MIN_CONC, MAX_CONC)
 Values
   ('Q235', 'Si', 0.03, 0.02, 0.04);
COMMIT;
